#68 multilang markup
gc-da11yn/gc-da11yn.github.io pull request #107
Opened 2021-11-24 15:50 UTC by csps-snap

## markdown pages language tagging

markdown pages need some french lang attribute so that they're being read properly.

**Related issues / Requêtes associées**
closes #68

2021-11-24 16:05 UTC, shawnthompson approved these changes

2021-11-24 16:11 UTC, csps-snap commented
huzzah

2021-12-02 19:07 UTC, duboisp approved these changes

2021-12-02 19:17 UTC, shawnthompson requested changes
Please make the changes

2021-12-02 19:17 UTC, shawnthompson commented on README.md
> +<div lang="en">
remove `<div lang="en">`

2021-12-02 19:17 UTC, shawnthompson commented on README.md
> +</div>
remove this line

2021-12-02 19:26 UTC, csps-snap commented on README.md
> +</div>
lines removed

2021-12-02 19:26 UTC, shawnthompson approved these changes

2021-12-02 19:27 UTC, merged