Google analytics
gc-da11yn/gc-da11yn.github.io pull request #303
Opened 2023-04-13 18:55 UTC by shawnthompson

This added the Google Analytics code to the `head` of the site.

Also doesn't show up on the staging Netlify sites.

2023-04-13 18:56 UTC, shawnthompson commented
@fredymoko Do we need to do anything in the GA dashboard to stop the analytics from collecting when we run the site locally / `localhost`?

2023-04-14 13:39 UTC, shawnthompson commented
I added an `if` condition to not load the GA script on `localhost`.

2023-04-18 16:16 UTC, duboisp requested changes
I propose this code variation which is safer

```html
<!-- Google tag (gtag.js) -->
<script>
( function( w ) {
"use strict";
	var dl = "dataLayer";
	if (w.location.hostname === "a11y.canada.ca") {
		w[dl] = w[dl] || [];
		w.gtag = function(){w[dl].push(arguments);}
		w.gtag('js', new Date());
		w.gtag('config', 'G-SM9MSHWDVN');
	}
} )( window );
</script>
```

2023-04-18 16:20 UTC, shawnthompson commented on src/_includes/partials/head.njk
> +			if (host != "localhost") {
It's using the the not dev environment but that's didn't handle `localhost`

```
{% if settings.env != "dev" %}
```

2023-04-18 16:21 UTC, shawnthompson commented on src/_includes/partials/head.njk
> +				function gtag() {
I'm not sure about that, I would assume yes.

2023-04-18 16:26 UTC, shawnthompson commented on src/_includes/partials/head.njk
> +			if (host != "localhost") {
Maybe I'll remove the environment condition.

2023-04-18 16:33 UTC, duboisp approved these changes

2023-04-18 16:33 UTC, merged