New site structure
gc-da11yn/gc-da11yn.github.io pull request #342
Opened 2023-09-08 19:46 UTC by acev0010

## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?
Add tags and creates sub-landing pages under /main/ folder for:

- about-us
- accessibility-fundamentals
- accessibility-in-the-government
- how-tos
- resources-and-tools

(Both English and French files)

## Additional information (optional) / Information additionnelle (optionel)

Running npm: start gives the following error: 

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering njk template ./src/main/en/about-us/contact-us.njk (via TemplateContentRenderError)
[11ty] 2. (./src/main/en/about-us/contact-us.njk)
[11ty]   TypeError: Cannot read properties of undefined (reading 'filter') (via Template render error)
```

This error happens with all the files I modified, I am unsure why it happens. 

I will leave this pull request open until I resolve this problem.

2023-09-08 20:53 UTC, acev0010 commented
Update: 

npm:start works now but the website isn't working properly.

When you go to a page, for example `about us > contact us` it doesn't take the user to the contact us page. Instead, it generates an extra page that loops the same page over and over again:

![image](https://github.com/gc-da11yn/gc-da11yn.github.io/assets/84023959/3fa5e9e9-bcec-43a0-ac5a-287279bb18c2)

I will come back to this next week

2023-09-11 17:28 UTC, shawnthompson commented
That would mean on the Contact Us page you are using `tags: contactUs`

2023-09-12 14:17 UTC, shawnthompson requested changes

2023-09-12 17:51 UTC, acev0010 commented on src/main/en/about-us/about-the-digital-the-accessibility-toolkit-project.njk
> +  - aboutTheDigitalTheAccessibilityToolkitProject
I removed the tags but ''contact us'' still loops around, is that normal?

2023-09-14 03:23 UTC, acev0010 commented
The following pages were either missing a sub-category or didn't have tags from the table:

**en:**

- mobility-flexibility-and-body-structure-disabilities.md
- universal-design-for-learning-udl.md

**fr:**

- conception-universelle-pour-lapprentissage-cua.md
- handicaps-cognitifs.md
- handicaps-de-mobilite-de-flexibilite-et-de-structure-corporelle.md
- mandats.md
- project-de-la-boite-a-outils-de-laccessibilite-numerique

2023-09-14 15:51 UTC, shawnthompson approved these changes

2023-09-14 15:54 UTC, merged