Restructured the about-disability page to most-common-type-of-disabilities
gc-da11yn/gc-da11yn.github.io pull request #420
Opened 2023-11-14 16:37 UTC by DhruvPatel2502

…ities

_(Pick the language of your choice to fill out the following information. / Choisissez la langue de votre choix pour remplir l'information ci-dessous.)_

## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?
A clear and concise description of what the code of this PR accomplishes. /// Une description claire et concise de ce que le code de cette PR accompli.

## Additional information (optional) / Information additionnelle (optionel)

**General checklist / Liste de contrôle générale**
Make your own list for the purpose of your Pull request. /// Faites votre propre liste en fonction des besoins de votre demande « pull ».

- [ ] Create/update documentation /// Créer/mettre à jour la documentation
- [ ] Build and test PR's code /// Rouler le script de compilation et tester le code de la PR
- [ ] Validate changes against WCAG for accessibility /// Valider les changements avec WCAG pour l'accessibilité
- [ ] Ensure documentation is bilingual /// S'assurer que la documentation soit bilingue

**Related issues / Requêtes associées**
List issues that are being closed or worked on with this pull request i.e. Closes #8941 /// Listez les autres requêtes (« issues » ou PR) qui sont fermées ou traitées avec cette demande de retrait ex. : Closes #8941

**Screenshots / Captures d'écrans**
If applicable, add screenshots to help demonstrate what this PR does. /// Si applicable, ajoutez des captures d'écran pour aider à démontrer ce que cette PR fait.

2023-11-14 16:39 UTC, DhruvPatel2502 commented
@JulieBB23 and @shawnthompson  Can you guys please take a look at this PR and let me know if there is any change needed?

2023-11-14 19:34 UTC, shawnthompson commented
Here's the link to the page:

[In development - Most Common Types of Disability - Digital Accessibility Toolkit / Sharing space](https://deploy-preview-420--a11ycanada.netlify.app/en/most-common-types-of-disability/)

2023-11-16 14:44 UTC, shawnthompson requested changes

2023-11-16 14:44 UTC, shawnthompson commented on src/pages/fr/deficiences-auditives.md
>  # Déficiences auditives
Remove the heading H1

2023-11-16 14:44 UTC, shawnthompson commented on src/pages/fr/deficiences-visuelles.md
>  # Déficiences visuelles
Remove the H1

2023-11-16 14:44 UTC, shawnthompson commented on src/pages/fr/handicaps-de-mobilite-de-flexibilite-et-de-structure-corporelle.md
>  # Handicaps de mobilité, de flexibilité et de structure corporelle
Remove the H1

2023-11-16 15:24 UTC, merged