Heading changes
gc-da11yn/gc-da11yn.github.io pull request #490
Opened 2023-11-30 16:07 UTC by acev0010

Test

2023-11-30 16:20 UTC, shawnthompson requested changes

2023-11-30 16:20 UTC, shawnthompson commented on src/_includes/partials/head.njk
> +	{% endif %}{% for item in tags %}{{ tagList.tags[locale][item] }}; {% endfor %}" />
Put this on the same line

2023-11-30 16:20 UTC, shawnthompson commented on src/_includes/partials/head.njk
> +	<meta name="dcterms.created" content="{{ src.gitCreatedDate }}" >
We should be able to pull this in without the changes to the .eleventy file

2023-11-30 16:20 UTC, shawnthompson commented on .eleventy.js
Might not need the changes in here.

2023-11-30 20:33 UTC, acev0010 commented
last commit fixes #344

2023-12-01 15:08 UTC, shawnthompson commented
Closes #466 #281 #344

2023-12-01 15:09 UTC, merged