Made the tip sheet pages in en and fr for creating accessible documents
gc-da11yn/gc-da11yn.github.io pull request #557
Opened 2024-01-19 14:46 UTC by DhruvPatel2502

## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?
Made the placeholder pages of tip sheets for Excel, Word, PPT and Outlook./ Réalisation des pages d'espace réservé des fiches-conseils pour Excel, Word, PPT et Outlook.

2024-01-19 14:52 UTC, shawnthompson requested changes
Can you add 'updatesMain' to the tags in the front matter to add it to the what's new section?

2024-01-19 14:53 UTC, DhruvPatel2502 commented
> Can you add 'updatesMain' to the tags in the front matter to add it to the what's new section?

ok on it

2024-01-31 15:18 UTC, shawnthompson commented on src/main/en/how-tos/ms-office-tip-sheets.njk
> +{% if collections.updatesMain === undefined %}
```suggestion
{% if collections.msTips === undefined %}
```

2024-01-31 15:19 UTC, shawnthompson commented on src/main/en/how-tos/ms-office-tip-sheets.njk
> +	{% for item in collections.updatesMain | sort(false, false, 'data.title') | localeMatch(locale) %}
```suggestion
	{% for item in collections.msTips | sort(false, false, 'data.title') | localeMatch(locale) %}
```

2024-01-31 15:19 UTC, shawnthompson commented on src/main/en/how-tos/ms-office-tip-sheets.njk
> +		{% if item.data.tags[1] != "updatesMain" %}
```suggestion
		{% if item.data.tags[1] != "msTips" %}
```

2024-01-31 15:20 UTC, shawnthompson commented on src/main/en/how-tos/ms-office-tip-sheets.njk
> +tags: howTos
```suggestion
tags:
  - howTos
  - updatesMain
```

2024-01-31 15:20 UTC, shawnthompson commented on src/main/fr/comment-faire/fiches-conseils-ms-office.njk
> +tags: howTos
```suggestion
tags:
  - howTos
  - updatesMain
```

2024-01-31 15:21 UTC, shawnthompson commented on src/main/fr/comment-faire/fiches-conseils-ms-office.njk
> +{% if collections.updatesMain === undefined %}
```suggestion
{% if collections.msTips === undefined %}
```

2024-01-31 15:22 UTC, shawnthompson commented on src/main/fr/comment-faire/fiches-conseils-ms-office.njk
> +	{% for item in collections.updatesMain | sort(false, false, 'data.title') | localeMatch(locale) %}
```suggestion
	{% for item in collections.msTips | sort(false, false, 'data.title') | localeMatch(locale) %}
```

2024-01-31 15:22 UTC, shawnthompson commented on src/main/fr/comment-faire/fiches-conseils-ms-office.njk
> +	{% if item.data.tags[1] != "updatesMain" %}
```suggestion
	{% if item.data.tags[1] != "msTips" %}
```

2024-01-31 15:22 UTC, shawnthompson commented on src/pages/en/ms-office-tip-sheets/tip-sheet-microsoft-excel.md
> +  - updatesMain
```suggestion
  - msTips
```

2024-01-31 15:22 UTC, shawnthompson commented on src/pages/en/ms-office-tip-sheets/tip-sheet-microsoft-powerpoint-Presentation.md
> +  - updatesMain
```suggestion
  - msTips
```

2024-01-31 15:23 UTC, shawnthompson commented on src/pages/en/ms-office-tip-sheets/tip-sheet-microsoft-word.md
> +  - updatesMain
```suggestion
  - msTips
```

2024-01-31 15:23 UTC, shawnthompson commented on src/pages/en/ms-office-tip-sheets/tip-sheet-outlook.md
> +  - updatesMain
```suggestion
  - msTips
```

2024-01-31 15:23 UTC, shawnthompson commented on src/pages/fr/fiches-conseils-ms-office/fiche-de-conseils-microsoft-excel.md
> +  - updatesMain
```suggestion
  - msTips
```

2024-01-31 15:23 UTC, shawnthompson commented on src/pages/fr/fiches-conseils-ms-office/fiche-de-conseils-microsoft-word.md
> +  - updatesMain
```suggestion
  - msTips
```

2024-01-31 15:23 UTC, shawnthompson commented on src/pages/fr/fiches-conseils-ms-office/fiche-de-conseils-outlook.md
> +  - updatesMain
```suggestion
  - msTips
```

2024-01-31 15:23 UTC, shawnthompson commented on src/pages/fr/fiches-conseils-ms-office/fiche-de-conseils-presentation-powerpoint-de-microsoft.md
> +  - updatesMain
```suggestion
  - msTips
```

2024-01-31 15:24 UTC, shawnthompson commented on src/_data/tagList.js
> +			updatesMain: "mise à jour sur le principal",
```suggestion
			msTips : "Fiches de conseils pour Microsoft Office",
```

2024-01-31 15:24 UTC, shawnthompson commented on src/_data/tagList.js
> +			updatesMain: "update on main",
```suggestion
			msTips: "Tip sheets for Microsoft Office",
```

2024-01-31 15:48 UTC, shawnthompson requested changes
Try this

2024-01-31 15:48 UTC, shawnthompson commented on src/main/en/how-tos/ms-office-tip-sheets.njk
> +  - howTos
```suggestion
  - createDocument
```

2024-01-31 15:48 UTC, shawnthompson commented on src/main/fr/comment-faire/fiches-conseils-ms-office.njk
> +  - howTos
```suggestion
  - createDocument
```

2024-01-31 15:48 UTC, shawnthompson commented on src/pages/en/ms-office-tip-sheets/tip-sheet-microsoft-excel.md
> +  - createDocument
```suggestion
  - createDocument
  - msTips
```

2024-01-31 15:48 UTC, shawnthompson commented on src/pages/en/ms-office-tip-sheets/tip-sheet-microsoft-powerpoint-Presentation.md
> +  - createDocument
```suggestion
  - createDocument
  - msTips
```

2024-01-31 15:48 UTC, shawnthompson commented on src/pages/en/ms-office-tip-sheets/tip-sheet-microsoft-word.md
> +  - createDocument
```suggestion
  - createDocument
  - msTips
```

2024-01-31 15:48 UTC, shawnthompson commented on src/pages/en/ms-office-tip-sheets/tip-sheet-outlook.md
> +  - createDocument
```suggestion
  - createDocument
  - msTips
```

2024-01-31 15:48 UTC, shawnthompson commented on src/pages/fr/fiches-conseils-ms-office/fiche-de-conseils-microsoft-excel.md
> +  - createDocument
```suggestion
  - createDocument
  - msTips
```

2024-01-31 15:48 UTC, shawnthompson commented on src/pages/fr/fiches-conseils-ms-office/fiche-de-conseils-microsoft-word.md
> +  - createDocument
```suggestion
  - createDocument
  - msTips
```

2024-01-31 15:48 UTC, shawnthompson commented on src/pages/fr/fiches-conseils-ms-office/fiche-de-conseils-outlook.md
> +  - createDocument
```suggestion
  - createDocument
  - msTips
```

2024-01-31 15:48 UTC, shawnthompson commented on src/pages/fr/fiches-conseils-ms-office/fiche-de-conseils-presentation-powerpoint-de-microsoft.md
> +  - createDocument
```suggestion
  - createDocument
  - msTips
```

2024-08-30 14:08 UTC, closed without merging